# These are supported funding model platforms

# github: [arthurkushman]
liberapay: arthurkushman
issuehunt: arthurkushman
patreon: user?u=26175584
bitcoin: 17ajxkGkwvx9HYqNVXRjQ91UiyAGcczRsi
ethereum: 0xd50929f0580cc58fbbcfb5db76316f883b2fb9fb